# Fichier de configuration principal pour le build Netlify
[build]
  # Dossier racine à publier après le build. "." signifie la racine du projet.
  publish = "."
  # Dossier où Netlify doit chercher les fonctions serverless.
  functions = "functions"

# Configuration spécifique aux fonctions serverless
[functions]
  # Spécifie les fichiers à inclure avec les fonctions lors du déploiement.
  # Essentiel pour que `analyze.py` puisse trouver les fichiers CSV.
  included_files = ["data_*.csv"]

# Règles de redirection
[[redirects]]
  # Cette règle redirige toutes les requêtes de /api/* vers la fonction correspondante.
  # Par exemple, un appel à /api/analyze sera traité par /.netlify/functions/analyze.
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
