[build]
  # Spécifie le nouveau dossier où se trouvent les fonctions
  functions = "functions"
  publish = "."

# La configuration de la fonction est maintenant héritée de la section [build]
# mais on peut la garder pour la clarté.
[functions]
  included_files = ["data_*.csv"]

# La redirection n'est plus critique car on utilise l'URL directe,
# mais c'est une bonne pratique de la laisser pour l'avenir.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
